### ISSUE TITLE
Add output dir option.

### ISSUE THREAD

**Issue by paco-valdez** [cube-js/lkml2cube#4]
When present, instead of printing to stdout it should create files in the following structure:

```
OUTPUT_DIR/
├── cubes/
│   ├── cube_1.yml
│   └── cube_2.yml
└── views/
    ├── cube_view_1.yml
    └── cube_view_2.yml
```

The command should be available to all commands (cubes and TBD).

- [x] cubes
- [x] TBD (command to parse explores)

**Comment by pacofvf** [comment]
Implemented in #5
